#
# AFFiNE DigitalOcean App Platform Deployment Spec
# Self-hosted knowledge base and collaboration platform
#
name: affine
region: sgp
services:
  # Main AFFiNE application server
  - name: affine-server
    github:
      repo: toeverything/AFFiNE
      branch: canary
      deploy_on_push: false
    dockerfile_path: .github/deployment/node/Dockerfile
    source_dir: /
    http_port: 3010
    instance_count: 1
    instance_size_slug: professional-xs
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: AFFINE_SERVER_PORT
        value: "3010"
      - key: AFFINE_SERVER_HOST
        value: affine.insightpulseai.net
      - key: AFFINE_SERVER_HTTPS
        value: "true"
      - key: AFFINE_INDEXER_ENABLED
        value: "false"
      - key: REDIS_SERVER_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${redis.HOSTNAME}
      - key: REDIS_SERVER_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${redis.PORT}
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "postgres://postgres.spdtwktxdalcfigzeqrz:SHWYXDMFAwXI1drT@aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true"
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: "https://spdtwktxdalcfigzeqrz.supabase.co"
      - key: SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwZHR3a3R4ZGFsY2ZpZ3plcXJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NDQwMzUsImV4cCI6MjA3NjIyMDAzNX0.IHBJ0cNTMKJvRozljqaEqWph_gC0zlW2Td5Xl_GENs4"
    routes:
      - path: /

  # Redis cache service
  - name: redis
    image:
      registry_type: DOCKER_HUB
      repository: redis
      tag: "7-alpine"
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 6379
    health_check:
      port: 6379
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3

# PostgreSQL database (using Supabase)
# Note: Using external Supabase PostgreSQL instead of DO managed database
# Connection via DATABASE_URL environment variable
# Project: xkxyvboeubffxxbebsll

# Deployment domains
domains:
  - domain: affine.insightpulseai.net
    type: PRIMARY
